# 上线配置文件
# 线上配置文件
server:
  port: 9999
spring:
  config:
    import: optional:file:.env[.properties]
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用Druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      # 连接池配置：大小，最小，最大
      initial-size: 20
      min-idle: 5
      max-active: 40
      # 连接等待超时时间
      max-wait: 50000
  # Redis 配置
  redis:
    database: ${REDIS_DATABASE}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 5000
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        time-between-eviction-runs: 10s
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''