# 开发配置文件
server:
  port: 8888
spring:
  config:
    import: optional:file:.env.dev[.properties]
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  # Redis 配置
  redis:
    database: ${REDIS_DATABASE}
    host: localhost
    port: 6379
    timeout: 5000
    password: ${REDIS_PASSWORD}
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456