# 公共配置文件
server:
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: WebOpenApi-core
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 开发者签名认证
web-open-api:
  client:
    access-key: f395fc296d5507b4d0ba8859468d3681
    secret-key: 2eec75616f6a65a3590e59a05d650ef3
# 配置dubbo
dubbo:
  application:
    name: webopenapi-core
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848