spring:
  config:
    import: optional:file:.env.dev[.properties]
# 配置dubbo
dubbo:
  application:
    name: webopenapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${NACOS_ADDRESS}:8848